import Head from "next/head";
import React from "react";
import LookLayout from "../../components/layouts/Look";

const Look = () => (
    <>
        <Head>
            <title>Наші образи</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <>
            <LookLayout />
        </>
    </>
);

export default Look;
