/* eslint-disable no-return-assign */
import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import { useFetchOneCollection } from "../../app/services/CollectionService/hooks";

import CollectionLayout from "../../components/layouts/Collection";

const Collection = () => {
    const router = useRouter();

    const collection = useFetchOneCollection(
        {
            enabled: router.isReady,
        },
        String(router.query.id),
    );

    return (
        <>
            <Head>
                <title>{collection?.data?.name}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <>
                <CollectionLayout
                    title={collection?.data?.name}
                    data={collection?.data?.products}
                    isLoading={collection.isLoading}
                    error={collection.error}
                />
            </>
        </>
    );
};

export default Collection;
