import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";

import { useFetchCategoryFilters } from "../../app/services/FilterService/hooks";
import CatalogLayout from "../../components/layouts/Catalog/CatalogLayout";

const CategoryCatalog = () => {
    const router = useRouter();
    const filters = useFetchCategoryFilters(String(router.query.category), {});

    if (!filters.data) {
        filters.refetch();
    }

    React.useEffect(() => {
        if (router.isReady) {
            filters.refetch();
        }
    }, [router.query]);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <>
                <CatalogLayout filters={filters} />
            </>
        </>
    );
};

export default CategoryCatalog;
