import Head from "next/head";
import React from "react";

import AdminDashboard from "../../components/layouts/Admin";

const Admin = () => (
    <>
        <Head>
            <title>Admin Dashboard</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
            <AdminDashboard />
        </div>
    </>
);

export default Admin;
