import Head from "next/head";
import React from "react";

import ProductLayout from "../../components/layouts/Product";

const Product = () => (
    <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />

            <link rel="icon" href="/favicon.ico" />
        </Head>
        <>
            <ProductLayout />
        </>
    </>
);

export default Product;
