import Head from "next/head";
import React from "react";
import { useAuthContext } from "../../app/providers/userProvider";

import AuthLayout from "../../components/layouts/Auth";
import ErrorPage from "../404";

const auth = () => {
    const user = useAuthContext();

    if (user.token && user.user) {
        return <ErrorPage />;
    }

    return (
        <>
            <Head>
                <title>Auth</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <>
                <AuthLayout />
            </>
        </>
    );
};

export default auth;
