import Head from "next/head";
import React from "react";
import BasketLayout from "../../components/layouts/Basket";

const Basket = () => (
    <>
        <Head>
            <title>Корзина</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <>
            <BasketLayout />
        </>
    </>
);

export default Basket;
