import Head from "next/head";
import React from "react";
import FavoriteLayout from "../../components/layouts/Favorite";

const Favorite = () => (
    <>
        <Head>
            <title>Збереженні товари</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <>
            <FavoriteLayout />
        </>
    </>
);

export default Favorite;
